{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "key-rotation-agent.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "key-rotation-agent.labels" . | nindent 4 }}
  annotations:
    # Prevent Helm from diffing secret values in plain text
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  {{- range $key, $val := .Values.secret.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
