podinfo:
  color: "#9c27b0"
secret:
  data:
    PASSWORD: "P7Jg5cuOeUNMmCfgrs0yO4OJVafRNtJP"
    UPDATED_AT: "2026-04-24 13:13 UTC"
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: "kra-delta.demo.local"
      paths:
        - path: /
          pathType: Prefix
