podinfo:
  color: "#e91e63"
secret:
  data:
    PASSWORD: "TFUo4G7sO8zANzbGP6v8csQY6Bhn5YMm"
    UPDATED_AT: "2026-04-24 13:28 UTC"
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: "kra-alpha.demo.local"
      paths:
        - path: /
          pathType: Prefix
