podinfo:
  color: "#ff9800"
secret:
  data:
    PASSWORD: "mrxUTlzKXxZtRvzluDXwIUXjDopAcWD2"
    UPDATED_AT: "2026-04-24 13:24 UTC"
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: "kra-gamma.demo.local"
      paths:
        - path: /
          pathType: Prefix
