podinfo:
  color: "#9c27b0"
secret:
  data:
    PASSWORD: "8SW830tykiHXQFjJp3yd7Hr1nFNdTJRn"
    UPDATED_AT: "2026-04-24 13:25 UTC"
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: "kra-delta.demo.local"
      paths:
        - path: /
          pathType: Prefix
