podinfo:
  color: "#e91e63"
secret:
  data:
    PASSWORD: "CwAZinSkpZ9nexYQ6snDS4yqTGNU1lLc"
    UPDATED_AT: "2026-04-24 13:22 UTC"
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: "kra-alpha.demo.local"
      paths:
        - path: /
          pathType: Prefix
