podinfo:
  color: "#ff9800"
secret:
  data:
    PASSWORD: "7ciNjf7Sl3QvW6J7bltynuKYnejjBkyC"
    UPDATED_AT: "2026-04-24 12:48 UTC"
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: "kra-gamma.demo.local"
      paths:
        - path: /
          pathType: Prefix
