podinfo:
  color: "#4caf50"
secret:
  data:
    PASSWORD: "YHSz71oKxbp5oOJy8H2nbAnoQeTlOr1C"
    UPDATED_AT: "2026-04-24 13:21 UTC"
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: "kra-beta.demo.local"
      paths:
        - path: /
          pathType: Prefix
